### ISSUE TITLE
Interest in generalization to 3d

### ISSUE THREAD

**Issue by benjijamorris** [ryanirl/torchvf#3]
Hey! I found your article very interesting and was curious if you've thought about extending these methods to the 3d case? If so, I'd be happy to help contribute.

**Comment by ryanirl** [comment]
I originally didn't explore the 3D case due to lack of computational resources. And *at the moment*, I don't have time to extend TorchVF to the 3d case, maybe in the future. That said, feel free to create a fork of the code and see if you can get it working if you want. Some of the code might already generalize to the 3d case naively (possibly the solvers, most the training/inference code, and clustering), although right off the bat you would have to figure out:
 1. Create a 3D U-Net.
 2. Ground truth 3d vector fields.
     - My SDF function is slow, maybe consider using Omnipose's EDT function.
 3. Modify interpolators to accept 3d inputs.
 4. Differentiation methods were built for 2d inputs.

**Comment by benjijamorris** [comment]
Sounds good, thanks!
